version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kasra123
      POSTGRES_DB: hdwallet
    ports:
      - 5432:5432
    networks:
      - hdwallet_network
  app:
    build: .
    restart: always
    ports:
      - 8088:8088
    networks:
      - hdwallet_network
    depends_on:
      - postgres
networks:
  hdwallet_network:
