version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: hdwallet
      MYSQL_ROOT_USERNAME: ''
      MYSQL_ROOT_PASSWORD: kasra123
    ports:
      - '3306:3306'
    networks:
      - hdwallet_network
  app:
    build: .
    restart: always
    ports:
      - 8088:8088
    networks:
      - hdwallet_network
    depends_on:
      - mysql

networks:
  hdwallet_network:
